# -*- coding: utf-8 -*-
"""Shared helpers for P9 MetroPT label, feature, and model artifacts."""
# 阅读提示：本模块集中维护 P9 的领域口径：传感器字典、weak label、交互特征和 minute features。
# 业务脚本应复用这里的函数，保证 CSV-derived 和 warehouse-derived 路径使用同一套特征定义。
# 学习导读：
# - 链路位置：P9/P10 领域公共层，连接 label builder、feature engineering、model experiments 和 warehouse parity。
# - 主要输入：Raw CSV、failure_windows、传感器定义和标准字段映射。
# - 主要输出：label frame、operating_state、interaction columns、minute feature table 和 TSV 工具。
# - 核心概念：P9 的核心学习对象是 weak-label minute features，不是逐条人工故障诊断记录。
# - 边界提醒：任何新增特征都应注意 leakage boundary，不能把未来窗口标签直接做成模型输入。
import os
import sys
import warnings
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple

import numpy as np
import pandas as pd
from pandas.errors import PerformanceWarning

warnings.filterwarnings("ignore", category=PerformanceWarning)

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from analysis_common import ANALOG_SENSORS, DIGITAL_SENSORS, load_config  # noqa: E402

ROOT_DIR = Path(__file__).resolve().parents[1]
SRC_DIR = ROOT_DIR / "src"
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

from metropt_utils import RAW_TO_STANDARD, parse_failure_windows, to_local_path  # noqa: E402


SENSOR_DETAILS: List[Dict[str, str]] = [
    # 传感器明细同时服务文档、EDA 和特征命名；raw_name 保留原始字段，standard_name 是代码统一列名。
    {
        "order": "1",
        "sensor_type": "analog",
        "raw_name": "TP2",
        "standard_name": "tp2",
        "unit": "bar",
        "physical_meaning": "Pressure measured on the compressor.",
        "value_meaning": "Continuous pressure signal.",
        "business_note": "Compressor-side pressure; useful for pressure generation and leak-behavior analysis.",
    },
    {
        "order": "2",
        "sensor_type": "analog",
        "raw_name": "TP3",
        "standard_name": "tp3",
        "unit": "bar",
        "physical_meaning": "Pressure generated at the pneumatic panel.",
        "value_meaning": "Continuous pressure signal.",
        "business_note": "Should stay close to reservoir pressure under stable operation.",
    },
    {
        "order": "3",
        "sensor_type": "analog",
        "raw_name": "H1",
        "standard_name": "h1",
        "unit": "bar",
        "physical_meaning": "Pressure generated by the pressure drop during cyclonic separator discharge.",
        "value_meaning": "Continuous pressure-drop related signal.",
        "business_note": "Useful for discharge behavior and pressure-drop anomaly analysis.",
    },
    {
        "order": "4",
        "sensor_type": "analog",
        "raw_name": "DV_pressure",
        "standard_name": "dv_pressure",
        "unit": "bar",
        "physical_meaning": "Pressure drop when air-dryer towers discharge.",
        "value_meaning": "Zero is expected when the compressor is operating under load.",
        "business_note": "Pairs with valve/electric signals to explain dryer discharge and loaded states.",
    },
    {
        "order": "5",
        "sensor_type": "analog",
        "raw_name": "Reservoirs",
        "standard_name": "reservoirs",
        "unit": "bar",
        "physical_meaning": "Downstream pressure of the reservoirs.",
        "value_meaning": "Continuous pressure signal, expected to be close to TP3.",
        "business_note": "Supports pressure-balance features such as tp3 - reservoirs.",
    },
    {
        "order": "6",
        "sensor_type": "analog",
        "raw_name": "Motor_current",
        "standard_name": "motor_current",
        "unit": "A",
        "physical_meaning": "Current of one phase of the three-phase motor.",
        "value_meaning": "About 0A off, 4A offloaded, 7A under load, and 9A starting.",
        "business_note": "Used to derive operating_state and explain load/offload cycles.",
    },
    {
        "order": "7",
        "sensor_type": "analog",
        "raw_name": "Oil_temperature",
        "standard_name": "oil_temperature",
        "unit": "C",
        "physical_meaning": "Oil temperature on the compressor.",
        "value_meaning": "Continuous temperature signal.",
        "business_note": "Thermal stress indicator; historically shows a large failure-window mean shift.",
    },
    {
        "order": "8",
        "sensor_type": "digital",
        "raw_name": "COMP",
        "standard_name": "comp",
        "unit": "0/1",
        "physical_meaning": "Electrical signal of the air-intake valve on the compressor.",
        "value_meaning": "Active when there is no air intake, indicating off or offloaded operation.",
        "business_note": "Useful with MPG and motor_current for state-machine behavior.",
    },
    {
        "order": "9",
        "sensor_type": "digital",
        "raw_name": "DV_eletric",
        "standard_name": "dv_electric",
        "unit": "0/1",
        "physical_meaning": "Electrical signal controlling the compressor outlet valve.",
        "value_meaning": "Active under load; inactive when off or offloaded.",
        "business_note": "Original CSV spelling is DV_eletric; the project standardizes it as dv_electric.",
    },
    {
        "order": "10",
        "sensor_type": "digital",
        "raw_name": "Towers",
        "standard_name": "towers",
        "unit": "0/1",
        "physical_meaning": "Signal defining which drying tower is operating and which is draining humidity.",
        "value_meaning": "Inactive means tower one; active means tower two.",
        "business_note": "Supports dryer-cycle and tower-switching analysis.",
    },
    {
        "order": "11",
        "sensor_type": "digital",
        "raw_name": "MPG",
        "standard_name": "mpg",
        "unit": "0/1",
        "physical_meaning": "Signal that starts the compressor under load by activating the intake valve.",
        "value_meaning": "Activates when APU pressure falls below about 8.2 bar.",
        "business_note": "Often shares behavior with COMP and indicates pressure-recovery demand.",
    },
    {
        "order": "12",
        "sensor_type": "digital",
        "raw_name": "LPS",
        "standard_name": "lps",
        "unit": "0/1",
        "physical_meaning": "Low-pressure switch signal.",
        "value_meaning": "Activates when pressure drops below about 7 bar.",
        "business_note": "Rare but operationally important low-pressure event indicator.",
    },
    {
        "order": "13",
        "sensor_type": "digital",
        "raw_name": "Pressure_switch",
        "standard_name": "pressure_switch",
        "unit": "0/1",
        "physical_meaning": "Electrical signal detecting discharge in the air-drying towers.",
        "value_meaning": "Binary discharge-detection signal.",
        "business_note": "Pairs with DV pressure and towers for dryer-discharge diagnostics.",
    },
    {
        "order": "14",
        "sensor_type": "digital",
        "raw_name": "Oil_level",
        "standard_name": "oil_level",
        "unit": "0/1",
        "physical_meaning": "Electrical signal detecting compressor oil level.",
        "value_meaning": "Active when oil is below expected values.",
        "business_note": "Maintenance and safety signal; do not treat as a continuous sensor.",
    },
    {
        "order": "15",
        "sensor_type": "digital",
        "raw_name": "Caudal_impulses",
        "standard_name": "caudal_impulses",
        "unit": "0/1",
        "physical_meaning": "Pulse output generated by the amount of air flowing from APU to reservoirs.",
        "value_meaning": "Binary pulse-style flow indicator in the provided CSV representation.",
        "business_note": "Useful for flow activity and state-transition features.",
    },
]


def active_config() -> Dict[str, Any]:
    """Load the active MetroPT config."""
    return load_config()


def configured_csv_path(config: Dict[str, Any]) -> Path:
    """Resolve the local CSV path from config."""
    raw_path = str(config.get("paths", {}).get("input_csv", "") or "")
    if not raw_path:
        raise FileNotFoundError("paths.input_csv is empty in the active MetroPT config.")
    # P9 CSV-derived 脚本使用 pandas 读取，所以即使配置写的是 file:// 或 Windows 路径，也要解析成本地 Path。
    path = Path(to_local_path(raw_path))
    if not path.exists():
        raise FileNotFoundError(f"MetroPT CSV does not exist: {path}")
    return path


def failure_window_records(config: Dict[str, Any]) -> List[Dict[str, Any]]:
    """Return configured failure windows as pandas-friendly records."""
    records = []
    for idx, (start, end, failure_type) in enumerate(parse_failure_windows(config), start=1):
        # failure_id 只用于文档和报告追踪窗口，不是原始数据集自带的故障编号。
        records.append(
            {
                "failure_id": idx,
                "start": pd.Timestamp(start),
                "end": pd.Timestamp(end),
                "failure_type": failure_type,
                "severity": "high_stress" if "high" in failure_type else "unknown",
            }
        )
    return records


def read_metropt_csv(config: Dict[str, Any], columns: Optional[Sequence[str]] = None) -> pd.DataFrame:
    """Read the MetroPT CSV and normalize columns to project standard names."""
    csv_path = configured_csv_path(config)
    raw_columns = None
    if columns is not None:
        requested_raw = []
        reverse_map = {standard: raw for raw, standard in RAW_TO_STANDARD.items()}
        reverse_map["dv_electric"] = "DV_eletric"
        for column in columns:
            # 调用方传标准字段名，底层读 CSV 时再映射回 raw header，避免业务脚本关心历史拼写。
            if column == "event_time":
                requested_raw.append("timestamp")
            elif column in reverse_map:
                requested_raw.append(reverse_map[column])
            else:
                requested_raw.append(column)
        raw_columns = list(dict.fromkeys(requested_raw))

    dtype_map = {}
    if raw_columns is None:
        for raw_name in RAW_TO_STANDARD:
            if raw_name != "timestamp":
                dtype_map[raw_name] = "float32"
    else:
        for raw_name in raw_columns:
            if raw_name != "timestamp":
                dtype_map[raw_name] = "float32"

    df = pd.read_csv(csv_path, usecols=raw_columns, dtype=dtype_map or None, parse_dates=["timestamp"])
    rename_map = {raw: standard for raw, standard in RAW_TO_STANDARD.items() if raw in df.columns}
    df = df.rename(columns=rename_map)
    if "event_time_raw" in df.columns:
        df = df.rename(columns={"event_time_raw": "event_time"})
    if "event_time" not in df.columns:
        raise ValueError("Normalized CSV is missing event_time.")
    df = df.sort_values("event_time").reset_index(drop=True)
    return df


def add_operating_state(df: pd.DataFrame) -> pd.DataFrame:
    """Add the project operating_state field from motor_current."""
    out = df.copy()
    current = pd.to_numeric(out["motor_current"], errors="coerce")
    out["operating_state"] = np.select(
        [current >= 7.0, current >= 1.0],
        ["loaded", "unloaded"],
        default="stopped",
    )
    return out


def build_label_frame(event_time: pd.Series, config: Dict[str, Any], post_window_hours: int = 24) -> pd.DataFrame:
    """Build P9 weak labels from configured failure intervals."""
    # 所有标签都由 configured failure windows 推导，是 weak labels；rul_seconds 只能作为离线 target/report 字段。
    times = pd.to_datetime(event_time)
    labels = pd.DataFrame({"event_time": times})
    for name in [
        "failure_window",
        "pre_failure_1h",
        "pre_failure_6h",
        "pre_failure_24h",
        "post_maintenance",
        "normal_candidate",
    ]:
        labels[name] = False
    labels["failure_type"] = "normal"
    labels["rul_seconds"] = np.nan

    records = failure_window_records(config)
    for record in records:
        start = record["start"]
        end = record["end"]
        failure_type = record["failure_type"]
        # failure_window 标记真实故障窗口；pre_failure_* 是故障前观察窗口，用于预测性维护 baseline。
        in_failure = (times >= start) & (times <= end)
        labels.loc[in_failure, "failure_window"] = True
        labels.loc[in_failure, "failure_type"] = failure_type

        labels.loc[(times >= start - pd.Timedelta(hours=1)) & (times < start), "pre_failure_1h"] = True
        labels.loc[(times >= start - pd.Timedelta(hours=6)) & (times < start), "pre_failure_6h"] = True
        labels.loc[(times >= start - pd.Timedelta(hours=24)) & (times < start), "pre_failure_24h"] = True
        labels.loc[(times > end) & (times <= end + pd.Timedelta(hours=post_window_hours)), "post_maintenance"] = True

    rul = pd.Series(np.nan, index=labels.index, dtype="float64")
    for record in records:
        start = record["start"]
        end = record["end"]
        before_start = (times < start) & rul.isna()
        # rul_seconds 是距离下一次已知故障窗口开始的离线派生字段，不能作为当前分类模型输入。
        rul.loc[before_start] = (start - times.loc[before_start]).dt.total_seconds()
        in_failure = (times >= start) & (times <= end)
        rul.loc[in_failure] = 0.0
    labels["rul_seconds"] = rul

    risk_or_recovery = (
        labels["failure_window"]
        | labels["pre_failure_24h"]
        | labels["post_maintenance"]
    )
    labels["normal_candidate"] = ~risk_or_recovery

    for name in ["failure_window", "pre_failure_1h", "pre_failure_6h", "pre_failure_24h", "post_maintenance", "normal_candidate"]:
        labels[name] = labels[name].astype("int8")
    return labels


def add_p9_labels(df: pd.DataFrame, config: Dict[str, Any]) -> pd.DataFrame:
    """Attach P9 labels to a normalized dataframe."""
    labels = build_label_frame(df["event_time"], config)
    out = df.copy()
    for column in labels.columns:
        if column == "event_time":
            continue
        out[column] = labels[column].values
    return out


def add_interaction_columns(df: pd.DataFrame) -> pd.DataFrame:
    """Add domain interaction features at raw-event grain."""
    out = df.copy()
    out["delta_tp3_reservoirs"] = out["tp3"] - out["reservoirs"]
    out["delta_tp2_tp3"] = out["tp2"] - out["tp3"]
    return out


def build_minute_feature_table(df: pd.DataFrame) -> pd.DataFrame:
    """Build right-aligned, minute-grain feature rows from normalized labeled events."""
    # 特征以 event_minute 为粒度，rolling window 均为 right-aligned，只使用当前和过去分钟。
    # label 列随表保留给离线评估和切片，模型入口必须在外层显式排除。
    required = set(ANALOG_SENSORS + DIGITAL_SENSORS + ["event_time"])
    missing = sorted(required - set(df.columns))
    if missing:
        raise ValueError(f"Cannot build P9 features; missing columns: {missing}")

    work = add_interaction_columns(add_operating_state(df))
    if "failure_window" not in work.columns:
        config = active_config()
        # 调用方若只给 raw readings，这里补标签；若已经带标签，则保持原口径不重复覆盖。
        work = add_p9_labels(work, config)
    work["event_minute"] = work["event_time"].dt.floor("min")
    work = work.sort_values("event_time").reset_index(drop=True)

    work["state_transition_flag"] = (work["operating_state"] != work["operating_state"].shift(1)).astype("int16")
    for sensor in DIGITAL_SENSORS:
        # toggle_count 捕捉开关量变化次数，常用于解释设备状态切换强度。
        work[f"toggle_{sensor}"] = work[sensor].diff().abs().fillna(0).astype("float32")

    named_aggs: Dict[str, Tuple[str, str]] = {
        "sample_count": ("event_time", "size"),
        "window_start": ("event_time", "min"),
        "window_end": ("event_time", "max"),
        "failure_window": ("failure_window", "max"),
        "pre_failure_1h": ("pre_failure_1h", "max"),
        "pre_failure_6h": ("pre_failure_6h", "max"),
        "pre_failure_24h": ("pre_failure_24h", "max"),
        "post_maintenance": ("post_maintenance", "max"),
        "normal_candidate": ("normal_candidate", "max"),
        "rul_seconds": ("rul_seconds", "min"),
        "state_transition_count": ("state_transition_flag", "sum"),
    }
    for state in ["loaded", "unloaded", "stopped"]:
        work[f"state_{state}"] = (work["operating_state"] == state).astype("int16")
        named_aggs[f"state_{state}_count"] = (f"state_{state}", "sum")
    for sensor in ANALOG_SENSORS + ["delta_tp3_reservoirs", "delta_tp2_tp3"]:
        named_aggs[f"mean_{sensor}"] = (sensor, "mean")
        named_aggs[f"std_{sensor}"] = (sensor, "std")
        named_aggs[f"min_{sensor}"] = (sensor, "min")
        named_aggs[f"max_{sensor}"] = (sensor, "max")
        named_aggs[f"first_{sensor}"] = (sensor, "first")
        named_aggs[f"last_{sensor}"] = (sensor, "last")
    for sensor in DIGITAL_SENSORS:
        named_aggs[f"active_count_{sensor}"] = (sensor, "sum")
        named_aggs[f"toggle_count_{sensor}"] = (f"toggle_{sensor}", "sum")

    minute = work.groupby("event_minute", observed=True).agg(**named_aggs).reset_index()
    duration_seconds = (minute["window_end"] - minute["window_start"]).dt.total_seconds().replace(0, np.nan)
    for sensor in ANALOG_SENSORS + ["delta_tp3_reservoirs", "delta_tp2_tp3"]:
        minute[f"slope_{sensor}"] = (minute[f"last_{sensor}"] - minute[f"first_{sensor}"]) / duration_seconds

    key_digital = ["comp", "dv_electric", "mpg", "lps", "pressure_switch", "oil_level"]
    base_numeric = [
        *(f"mean_{sensor}" for sensor in ANALOG_SENSORS),
        *(f"std_{sensor}" for sensor in ANALOG_SENSORS),
        "mean_delta_tp3_reservoirs",
        "mean_delta_tp2_tp3",
        "state_transition_count",
        *(f"toggle_count_{sensor}" for sensor in key_digital),
        *(f"active_count_{sensor}" for sensor in key_digital),
    ]
    base_numeric = [col for col in base_numeric if col in minute.columns]
    minute = minute.sort_values("event_minute").reset_index(drop=True)
    quantile_cols = [
        *(f"mean_{sensor}" for sensor in ANALOG_SENSORS),
        "mean_delta_tp3_reservoirs",
        "mean_delta_tp2_tp3",
    ]
    quantile_cols = [col for col in quantile_cols if col in minute.columns]
    for window in [1, 5, 15, 60]:
        # rolling 以当前分钟为右边界，只聚合当前和历史分钟，避免把未来信息泄漏进特征。
        roll = minute[base_numeric].rolling(window=window, min_periods=1)
        for col in base_numeric:
            minute[f"roll{window}_mean_{col}"] = roll[col].mean()
            if window > 1:
                minute[f"roll{window}_std_{col}"] = roll[col].std().fillna(0.0)
                minute[f"roll{window}_min_{col}"] = roll[col].min()
                minute[f"roll{window}_max_{col}"] = roll[col].max()
        if window in {15, 60}:
            qroll = minute[quantile_cols].rolling(window=window, min_periods=1)
            for col in quantile_cols:
                minute[f"roll{window}_q25_{col}"] = qroll[col].quantile(0.25)
                minute[f"roll{window}_q75_{col}"] = qroll[col].quantile(0.75)
    return minute


def relative_path(path: Path) -> str:
    """Return a project-relative artifact path."""
    try:
        return str(path.relative_to(ROOT_DIR)).replace("\\", "/")
    except ValueError:
        return str(path)


def write_tsv(path: Path, rows: Iterable[Dict[str, Any]], columns: Sequence[str]) -> Path:
    """Write small tab-separated metadata artifacts."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\t".join(columns) + "\n")
        for row in rows:
            f.write("\t".join("" if row.get(col) is None else str(row.get(col)) for col in columns) + "\n")
    return path
